-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- Snapshot: 2026-07-05 (re-export from Supabase when schema changes)

CREATE TABLE public.deals (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  negocio_num text,
  cliente_nombre text,
  cliente_rif text,
  vendedor text,
  banco text,
  fecha_entrega date,
  stock_num text,
  vin text,
  tasa_bcv numeric,
  tasa_variable numeric,
  precio_vehiculo numeric DEFAULT 0,
  iva numeric DEFAULT 0,
  gastos_admin numeric DEFAULT 0,
  seguro numeric DEFAULT 0,
  accesorios numeric DEFAULT 0,
  placas numeric DEFAULT 0,
  igtf numeric DEFAULT 0,
  comision_banco numeric DEFAULT 0,
  monto_financiar numeric DEFAULT 0,
  total_cliente numeric DEFAULT 0,
  total_recibido numeric DEFAULT 0,
  resultado numeric DEFAULT 0,
  resultado_tipo text,
  status text DEFAULT 'borrador'::text,
  seguro_2do_ano boolean DEFAULT false,
  seguro_2do_ano_monto numeric DEFAULT 0,
  pagos jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  pv_precio numeric DEFAULT 0,
  pv_gastos_admin numeric DEFAULT 0,
  pv_seguro numeric DEFAULT 0,
  pv_igtf numeric DEFAULT 0,
  pv_accesorios numeric DEFAULT 0,
  pv_placas numeric DEFAULT 0,
  pv_inicial numeric DEFAULT 0,
  pv_monto_financiar numeric DEFAULT 0,
  pv_comision_banco numeric DEFAULT 0,
  pv_comision_flat_cobrado numeric DEFAULT 0,
  au_precio numeric DEFAULT 0,
  au_gastos_admin numeric DEFAULT 0,
  au_seguro numeric DEFAULT 0,
  au_igtf numeric DEFAULT 0,
  au_accesorios numeric DEFAULT 0,
  au_comision_flat numeric DEFAULT 0,
  au_placas numeric DEFAULT 0,
  fecha_factura date,
  cliente_rif_tipo text DEFAULT 'V'::text,
  ajuste_cuadre numeric DEFAULT 0,
  nota_entrega_at timestamp with time zone,
  comprobantes jsonb DEFAULT '[]'::jsonb,
  unlock_reason text,
  unlocked_by uuid,
  unlocked_at timestamp with time zone,
  cliente_apellidos text,
  cliente_direccion text,
  cliente_telefono text,
  cliente_email text,
  cliente_estado_civil text,
  vehiculo_marca text,
  vehiculo_modelo text,
  vehiculo_color text,
  vehiculo_placa text,
  vehiculo_año integer,
  vehiculo_clase text,
  vehiculo_uso text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  vehiculo_año_fabricacion integer,
  inventory_vin text,
  inventory_linked_at timestamp with time zone,
  inventory_linked_by uuid,
  factura_venta_body_neto numeric,
  factura_venta_iva numeric,
  factura_venta_igtf_real numeric,
  factura_venta_placa numeric,
  factura_venta_total numeric,
  factura_venta_fecha date,
  factura_venta_numero text,
  factura_venta_control text,
  factura_venta_modo_igtf text CHECK (factura_venta_modo_igtf IS NULL OR (factura_venta_modo_igtf = ANY (ARRAY['embebido'::text, 'separado'::text, 'no_aplica'::text]))),
  factura_compra_body_neto numeric,
  factura_compra_iva numeric,
  factura_compra_igtf numeric,
  factura_compra_placa numeric,
  factura_compra_total numeric,
  factura_compra_tasa_bcv numeric,
  factura_compra_fecha date,
  seguro_pagado_supplier numeric DEFAULT 0,
  accesorios_pagado_supplier numeric DEFAULT 0,
  real_funding_amount numeric,
  documentos_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  factura_venta_tasa_bcv numeric,
  gastos_admin_cobrado numeric DEFAULT 0,
  seguro_cobrado numeric DEFAULT 0,
  accesorios_cobrado numeric DEFAULT 0,
  comision_cobrada_cliente numeric DEFAULT 0,
  unverified_override_reason text,
  unverified_override_by uuid,
  unverified_override_at timestamp with time zone,
  vin_legacy_backup text,
  seguro_real_monto numeric,
  seguro_real_at timestamp with time zone,
  seguro_real_ref text,
  seguro_real_by text,
  factura_compra_numero text,
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_unverified_override_by_fkey FOREIGN KEY (unverified_override_by) REFERENCES auth.users(id),
  CONSTRAINT deals_inventory_vin_fkey FOREIGN KEY (inventory_vin) REFERENCES public.inventory_units(vin),
  CONSTRAINT deals_inventory_linked_by_fkey FOREIGN KEY (inventory_linked_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'manager'::text, 'user'::text, 'auditoria'::text, 'auditoria_ingresos'::text, 'administrador'::text, 'gerente'::text, 'jefe_ventas'::text, 'asesor_ventas'::text, 'gte_cobranza'::text, 'asist_cobranza'::text, 'asist_admin'::text, 'bdc'::text, 'cliente'::text, 'tesoreria'::text, 'facturacion'::text])),
  created_at timestamp with time zone DEFAULT now(),
  email text,
  full_name text,
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamp with time zone,
  crm_role text,
  npa_can_view_crm boolean DEFAULT false,
  npa_can_view_management_pnl boolean DEFAULT false,
  telefono_wa text,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  cedula_tipo text DEFAULT 'V'::text,
  cedula_num text NOT NULL,
  fecha_nacimiento text,
  direccion text,
  email text,
  telefono text,
  ocupacion text,
  cedula_imagen text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  tipo_cliente text NOT NULL DEFAULT 'natural'::text,
  rif text,
  razon_social text,
  CONSTRAINT clientes_pkey PRIMARY KEY (id),
  CONSTRAINT clientes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.cobranza_contratos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_nombre text NOT NULL,
  cliente_cedula text,
  fiador text,
  modelo text,
  placa text,
  precio_venta numeric DEFAULT 0,
  inicial numeric DEFAULT 0,
  saldo_financiar numeric DEFAULT 0,
  interes_pct numeric DEFAULT 0,
  nro_cuotas integer DEFAULT 12,
  monto_cuota numeric DEFAULT 0,
  fecha_venta date,
  fecha_primera_cuota date,
  notas text,
  status text DEFAULT 'ACTIVO'::text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  prestatario_tipo text DEFAULT 'persona'::text,
  empresa_razon_social text,
  empresa_rif text,
  empresa_registro_mercantil text,
  empresa_rep_legal_nombre text,
  empresa_rep_legal_cedula text,
  cliente_apellidos text,
  cliente_estado_civil text,
  cliente_direccion text,
  cliente_ciudad text DEFAULT 'Maracay'::text,
  cliente_estado text DEFAULT 'Aragua'::text,
  cliente_telefono text,
  cliente_email text,
  fiador_cedula text,
  fiador_estado_civil text,
  fiador_direccion text,
  fiador_ciudad text,
  fiador_estado text DEFAULT 'Aragua'::text,
  fiador_telefono text,
  fiador_email text,
  vehiculo_marca text DEFAULT 'KIA'::text,
  vehiculo_anio_fabricacion integer,
  vehiculo_anio_modelo integer,
  vehiculo_color text,
  vehiculo_clase text,
  vehiculo_tipo text,
  vehiculo_uso text DEFAULT 'PARTICULAR'::text,
  vehiculo_serial_motor text,
  vehiculo_serial_niv text,
  cuota_mensual_usd numeric,
  costo_tramites_usd numeric DEFAULT 800,
  tasa_cambio_bcv numeric,
  fecha_tasa_cambio date,
  fecha_contrato date,
  factura_numero text,
  vehiculo_serial_carroceria text,
  cliente_user_id uuid,
  saldo_financiar_negociacion numeric,
  precio_venta_factura numeric,
  pickup_monto numeric,
  pickup_fecha date,
  solicitud_id uuid,
  saldo_a_favor numeric NOT NULL DEFAULT 0,
  empresa_firmantes jsonb,
  acta_analisis jsonb,
  incluir_conyuge boolean NOT NULL DEFAULT false,
  conyuge_nombre text,
  conyuge_cedula text,
  conyuge_estado_civil text,
  conyuge_direccion text,
  conyuge_ciudad text,
  conyuge_estado text,
  conyuge_telefono text,
  conyuge_email text,
  acta_override boolean NOT NULL DEFAULT false,
  acta_override_reason text,
  acta_override_by uuid,
  acta_override_at timestamp with time zone,
  deal_id bigint,
  CONSTRAINT cobranza_contratos_pkey PRIMARY KEY (id),
  CONSTRAINT cobranza_contratos_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT cobranza_contratos_cliente_user_id_fkey FOREIGN KEY (cliente_user_id) REFERENCES auth.users(id),
  CONSTRAINT cobranza_contratos_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_prestamo(id),
  CONSTRAINT cobranza_contratos_acta_override_by_fkey FOREIGN KEY (acta_override_by) REFERENCES auth.users(id),
  CONSTRAINT cobranza_contratos_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id)
);
CREATE TABLE public.cobranza_cuotas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contrato_id uuid,
  cuota_num integer NOT NULL,
  cuota_label text,
  fecha_vencimiento date NOT NULL,
  monto_cuota numeric NOT NULL DEFAULT 0,
  fecha_pago date,
  monto_pagado numeric DEFAULT 0,
  metodo_pago text,
  observaciones text,
  status text DEFAULT 'PENDIENTE'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  saldo_inicial_usd numeric,
  principal_usd numeric,
  saldo_fin_usd numeric,
  referencia_pago text,
  comprobante_url text,
  confirmado_por text,
  notas_pago text,
  aprobado_por text,
  aprobado_at timestamp with time zone,
  rechazo_motivo text,
  recibo_url text,
  recibo_numero text,
  recibo_emitido_at timestamp with time zone,
  tesoreria_comprobante_id uuid,
  allocation_group_id uuid,
  source_app text DEFAULT 'Portal'::text CHECK (source_app IS NULL OR (source_app = ANY (ARRAY['Portal'::text, 'Cliente'::text]))),
  tes_compr_id uuid,
  alloc_group_id uuid,
  CONSTRAINT cobranza_cuotas_pkey PRIMARY KEY (id),
  CONSTRAINT cobranza_cuotas_contrato_id_fkey FOREIGN KEY (contrato_id) REFERENCES public.cobranza_contratos(id),
  CONSTRAINT cobranza_cuotas_tes_compr_id_fkey FOREIGN KEY (tes_compr_id) REFERENCES public.tesoreria_comprobantes(id)
);
CREATE TABLE public.crm_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  apellidos text NOT NULL,
  cedula text,
  telefono text NOT NULL,
  email text,
  cedula_prefix text DEFAULT 'V'::text,
  fuente text NOT NULL DEFAULT 'walk_in'::text,
  referido_por text,
  asignado_a uuid,
  asignado_nombre text,
  modelo_interes text,
  version_interes text,
  presupuesto_usd numeric,
  color_preferido text,
  tiene_vehiculo boolean DEFAULT false,
  vehiculo_actual text,
  etapa text NOT NULL DEFAULT 'nuevo'::text,
  motivo_perdido text,
  heat_score integer DEFAULT 50,
  ultimo_contacto timestamp with time zone,
  proxima_accion text,
  proxima_accion_at timestamp with time zone,
  notas text,
  contrato_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  origen_carga text NOT NULL DEFAULT 'organico'::text,
  ai_score integer,
  ai_close_prob integer,
  ai_reason text,
  ai_scored_at timestamp with time zone,
  ciudad text,
  solid_alerted boolean NOT NULL DEFAULT false,
  esperando_contacto_at timestamp with time zone,
  contacted_at timestamp with time zone,
  escalated_at timestamp with time zone,
  assigned_executive text,
  archived_at timestamp with time zone,
  campana text,
  meta_ad_id text,
  contacted_by uuid,
  contacted_by_nombre text,
  assigned_manual boolean DEFAULT false,
  reassigned_at timestamp with time zone,
  gestionado_at timestamp with time zone,
  escalation_line text,
  escalation_rung integer NOT NULL DEFAULT 0,
  heat_reason text,
  heat_updated_at timestamp with time zone,
  lead_resumen text,
  CONSTRAINT crm_leads_pkey PRIMARY KEY (id),
  CONSTRAINT crm_leads_asignado_a_fkey FOREIGN KEY (asignado_a) REFERENCES auth.users(id),
  CONSTRAINT crm_leads_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.crm_actividades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  tipo text NOT NULL,
  descripcion text NOT NULL,
  resultado text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_actividades_pkey PRIMARY KEY (id),
  CONSTRAINT crm_actividades_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id),
  CONSTRAINT crm_actividades_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.crm_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid,
  wa_phone text NOT NULL,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'resolved'::text, 'pending'::text])),
  bot_active boolean DEFAULT true,
  bot_mode text DEFAULT 'full'::text CHECK (bot_mode = ANY (ARRAY['full'::text, 'assist'::text, 'off'::text])),
  assigned_to uuid,
  assigned_nombre text,
  unread_count integer DEFAULT 0,
  last_message_at timestamp with time zone DEFAULT now(),
  last_message_preview text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_in_at timestamp with time zone,
  nudge1_at timestamp with time zone,
  nudge2_at timestamp with time zone,
  reengage_stage integer NOT NULL DEFAULT 0,
  reengage_last_at timestamp with time zone,
  holding_reassured_at timestamp with time zone,
  fotos_enviadas text[] NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT crm_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT crm_conversations_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id),
  CONSTRAINT crm_conversations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.crm_mensajes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  lead_id uuid,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['in'::text, 'out'::text])),
  content text,
  media_url text,
  media_type text,
  wa_message_id text UNIQUE,
  status text DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['received'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text])),
  sent_by text DEFAULT 'system'::text,
  sent_by_nombre text,
  is_bot boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_mensajes_pkey PRIMARY KEY (id),
  CONSTRAINT crm_mensajes_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.crm_conversations(id),
  CONSTRAINT crm_mensajes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id)
);
CREATE TABLE public.crm_bot_flows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  trigger text NOT NULL CHECK (trigger = ANY (ARRAY['new_lead'::text, 'no_response'::text, 'keyword'::text, 'manual'::text])),
  trigger_value text,
  is_active boolean DEFAULT true,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_bot_flows_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_followup_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  sequence_step integer NOT NULL,
  trigger_type text NOT NULL,
  mensaje_texto text,
  wa_status text DEFAULT 'sent'::text,
  sent_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_followup_log_pkey PRIMARY KEY (id),
  CONSTRAINT crm_followup_log_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id)
);
CREATE TABLE public.crm_etapa_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  etapa_anterior text,
  etapa_nueva text NOT NULL,
  changed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_etapa_log_pkey PRIMARY KEY (id),
  CONSTRAINT crm_etapa_log_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id)
);
CREATE TABLE public.crm_stage_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  from_etapa text,
  to_etapa text NOT NULL,
  changed_by uuid,
  source text NOT NULL DEFAULT 'user'::text,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_stage_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_citas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  fecha date NOT NULL,
  hora time without time zone,
  asignado_a uuid,
  asignado_nombre text,
  estado text NOT NULL DEFAULT 'agendada'::text,
  notas text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reminder_dia_at timestamp with time zone,
  reminder_horas_at timestamp with time zone,
  CONSTRAINT crm_citas_pkey PRIMARY KEY (id),
  CONSTRAINT crm_citas_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id)
);
CREATE TABLE public.crm_tareas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid,
  asignado_a uuid,
  asignado_nombre text,
  titulo text NOT NULL,
  notas text,
  tipo text NOT NULL DEFAULT 'llamada'::text CHECK (tipo = ANY (ARRAY['llamada'::text, 'whatsapp'::text, 'visita'::text, 'email'::text, 'seguimiento'::text, 'otro'::text])),
  remind_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'pendiente'::text CHECK (status = ANY (ARRAY['pendiente'::text, 'completada'::text, 'cancelada'::text])),
  origen text NOT NULL DEFAULT 'manual'::text,
  wa_enviado boolean NOT NULL DEFAULT false,
  wa_enviado_at timestamp with time zone,
  wa_message_id text,
  wa_status text,
  resultado text,
  completada_at timestamp with time zone,
  completada_por uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_tareas_pkey PRIMARY KEY (id),
  CONSTRAINT crm_tareas_completada_por_fkey FOREIGN KEY (completada_por) REFERENCES auth.users(id),
  CONSTRAINT crm_tareas_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT crm_tareas_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id),
  CONSTRAINT crm_tareas_asignado_a_fkey FOREIGN KEY (asignado_a) REFERENCES auth.users(id)
);
CREATE TABLE public.crm_supervisor_findings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid,
  lead_nombre text,
  asesor text,
  asesor_id uuid,
  tipo text NOT NULL,
  detalle text,
  accion text,
  urgencia text,
  estado text NOT NULL DEFAULT 'open'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT crm_supervisor_findings_pkey PRIMARY KEY (id),
  CONSTRAINT crm_supervisor_findings_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.crm_leads(id)
);
CREATE TABLE public.crm_bot_state (
  k text NOT NULL,
  v text,
  CONSTRAINT crm_bot_state_pkey PRIMARY KEY (k)
);
CREATE TABLE public.bank_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cuenta text NOT NULL CHECK (cuenta = ANY (ARRAY['roframi'::text, 'roframi_regions'::text, 'motocentro'::text, 'panama'::text, 'bolivares'::text, 'UNKNOWN'::text])),
  fecha date,
  monto_usd numeric,
  monto_bs numeric,
  sender_name text,
  referencia text,
  tipo text CHECK (tipo = ANY (ARRAY['zelle'::text, 'wire'::text, 'ach'::text, 'deposit'::text, 'transfer_out'::text, 'card_charge'::text, 'bank_fee'::text, 'transfer_in'::text, 'other'::text])),
  descripcion text,
  raw_text text,
  deal_id bigint,
  matched boolean DEFAULT false,
  is_third_party boolean DEFAULT false,
  statement_month text,
  source text CHECK (source = ANY (ARRAY['screenshot'::text, 'pdf_statement'::text, 'manual'::text, 'bofa_email'::text, 'bank_email'::text, 'bank_sms'::text, 'admin_quick_recon'::text])),
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  suggested_as_ingreso boolean DEFAULT false,
  ingreso_confirmed boolean DEFAULT false,
  ingreso_confirmed_by uuid,
  ingreso_confirmed_at timestamp with time zone,
  direccion text DEFAULT 'credit'::text CHECK (direccion = ANY (ARRAY['credit'::text, 'debit'::text])),
  es_bancarizacion boolean DEFAULT false,
  banc_depositante text,
  banc_es_tercero boolean DEFAULT false,
  banc_comision_usd numeric DEFAULT 0,
  es_compra_unidades boolean DEFAULT false,
  compra_proveedor text,
  categoria_gasto text,
  proveedor text,
  is_internal boolean NOT NULL DEFAULT false,
  is_bank_fee boolean NOT NULL DEFAULT false,
  referencia_alt text,
  payment_memo text,
  flujo text CHECK (flujo = ANY (ARRAY['ingreso'::text, 'egreso'::text])),
  reversed_at timestamp with time zone,
  reversed_by_comprobante_id uuid,
  pago_recibido_id uuid,
  cuenta_id text,
  seen_in_email boolean NOT NULL DEFAULT false,
  seen_in_statement boolean NOT NULL DEFAULT false,
  seen_in_screenshot boolean NOT NULL DEFAULT false,
  sources_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  excluida_revision boolean DEFAULT false,
  CONSTRAINT bank_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT bank_transactions_pago_recibido_id_fkey FOREIGN KEY (pago_recibido_id) REFERENCES public.pagos_recibidos(id),
  CONSTRAINT bank_transactions_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT bank_transactions_reversed_by_comprobante_id_fkey FOREIGN KEY (reversed_by_comprobante_id) REFERENCES public.tesoreria_comprobantes(id),
  CONSTRAINT bank_transactions_cuenta_id_fkey FOREIGN KEY (cuenta_id) REFERENCES public.cuentas_bancarias(id)
);
CREATE TABLE public.inventory_units (
  vin text NOT NULL,
  modelo text NOT NULL,
  año integer NOT NULL,
  color text,
  motor_serial text,
  placa text,
  factura_compra_num text NOT NULL,
  factura_compra_control_num text,
  factura_compra_fecha date NOT NULL,
  costo_unidad_usd numeric NOT NULL CHECK (costo_unidad_usd >= 0::numeric),
  costo_placa_certificado_usd numeric DEFAULT 0 CHECK (costo_placa_certificado_usd >= 0::numeric),
  costo_total_factura_usd numeric,
  estado text NOT NULL DEFAULT 'EN_STOCK'::text CHECK (estado = ANY (ARRAY['EN_STOCK'::text, 'ASIGNADO'::text, 'PENDING_FUNDING'::text, 'VENDIDO'::text, 'ENTREGADO'::text, 'VOIDED'::text])),
  fecha_entrada date NOT NULL DEFAULT CURRENT_DATE,
  fecha_asignacion date,
  fecha_venta date,
  fecha_entrega date,
  factura_compra_pdf_url text,
  factura_compra_image_url text,
  notas text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inventory_units_pkey PRIMARY KEY (vin),
  CONSTRAINT inventory_units_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT inventory_units_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.kia_modelos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  modelo text NOT NULL UNIQUE,
  segmento text,
  motor text,
  potencia text,
  transmision text,
  puestos text,
  destacados text,
  activo boolean DEFAULT true,
  orden integer DEFAULT 100,
  updated_at timestamp with time zone DEFAULT now(),
  precio_desde numeric,
  versiones jsonb,
  CONSTRAINT kia_modelos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.binance_rates (
  fecha date NOT NULL,
  rate_usdt_ves numeric NOT NULL,
  source text DEFAULT 'binance_p2p_buy_median'::text,
  fetched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT binance_rates_pkey PRIMARY KEY (fecha)
);
CREATE TABLE public.bcv_rates (
  fecha date NOT NULL,
  rate_usd_ves numeric NOT NULL,
  source text DEFAULT 'bcv_oficial'::text,
  fetched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bcv_rates_pkey PRIMARY KEY (fecha)
);
CREATE TABLE public.meta_ad_insights (
  fecha date NOT NULL,
  ad_id text NOT NULL,
  ad_name text,
  adset_id text,
  adset_name text,
  campaign_id text,
  campaign_name text,
  account_id text,
  currency text,
  spend numeric NOT NULL DEFAULT 0,
  impressions bigint NOT NULL DEFAULT 0,
  clicks bigint NOT NULL DEFAULT 0,
  link_clicks bigint,
  reach bigint,
  frequency numeric,
  ctr numeric,
  cpc numeric,
  cpm numeric,
  meta_leads integer,
  meta_messaging_started integer,
  actions jsonb,
  cost_per_action jsonb,
  fetched_at timestamp with time zone NOT NULL DEFAULT now(),
  objective text,
  CONSTRAINT meta_ad_insights_pkey PRIMARY KEY (fecha, ad_id)
);
CREATE TABLE public.meta_ad_breakdowns (
  fecha date NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text,
  breakdown_type text NOT NULL,
  dim1 text NOT NULL DEFAULT ''::text,
  dim2 text NOT NULL DEFAULT ''::text,
  spend numeric NOT NULL DEFAULT 0,
  impressions bigint NOT NULL DEFAULT 0,
  clicks bigint NOT NULL DEFAULT 0,
  meta_leads integer NOT NULL DEFAULT 0,
  meta_messaging_started integer NOT NULL DEFAULT 0,
  account_id text,
  fetched_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_ad_breakdowns_pkey PRIMARY KEY (fecha, campaign_id, breakdown_type, dim1, dim2)
);
CREATE TABLE public.comunicaciones_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contrato_id uuid,
  cuota_id uuid,
  cliente_nombre text,
  telefono text NOT NULL,
  mensaje_tipo text NOT NULL CHECK (mensaje_tipo = ANY (ARRAY['proxima_a_vencer'::text, 'vencida'::text, 'general'::text, 'bienvenida_portal'::text])),
  mensaje_texto text NOT NULL,
  whatsapp_message_id text,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text])),
  error_detalle text,
  enviado_por uuid,
  enviado_at timestamp with time zone DEFAULT now(),
  canal text NOT NULL DEFAULT 'whatsapp'::text,
  asunto text,
  CONSTRAINT comunicaciones_log_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_log_contrato_id_fkey FOREIGN KEY (contrato_id) REFERENCES public.cobranza_contratos(id),
  CONSTRAINT whatsapp_log_cuota_id_fkey FOREIGN KEY (cuota_id) REFERENCES public.cobranza_cuotas(id),
  CONSTRAINT whatsapp_log_enviado_por_fkey FOREIGN KEY (enviado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.whatsapp_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  direction text NOT NULL DEFAULT 'outbound'::text,
  to_phone text,
  to_name text,
  msg_type text,
  template_name text,
  evento text,
  body text,
  status text NOT NULL DEFAULT 'sent'::text,
  meta_message_id text,
  error_msg text,
  triggered_by text,
  recipients_role text,
  raw_response jsonb,
  inserted_by uuid,
  CONSTRAINT whatsapp_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  user_email text,
  action text NOT NULL,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  can_view_prestamos boolean NOT NULL DEFAULT false,
  can_create_prestamos boolean NOT NULL DEFAULT false,
  can_edit_prestamos boolean NOT NULL DEFAULT false,
  can_delete_prestamos boolean NOT NULL DEFAULT false,
  can_register_pagos boolean NOT NULL DEFAULT false,
  can_verify_pagos boolean NOT NULL DEFAULT false,
  can_send_whatsapp boolean NOT NULL DEFAULT false,
  can_view_whatsapp_log boolean NOT NULL DEFAULT false,
  can_view_reportes boolean NOT NULL DEFAULT false,
  can_view_crm boolean NOT NULL DEFAULT false,
  can_manage_crm boolean NOT NULL DEFAULT false,
  can_view_inventory boolean NOT NULL DEFAULT false,
  can_manage_inventory boolean NOT NULL DEFAULT false,
  can_manage_settings boolean NOT NULL DEFAULT false,
  npa_can_view_dashboard boolean NOT NULL DEFAULT false,
  npa_can_view_clientes boolean NOT NULL DEFAULT false,
  npa_can_view_deals boolean NOT NULL DEFAULT false,
  npa_can_audit_deals boolean NOT NULL DEFAULT false,
  npa_can_view_cobranza boolean NOT NULL DEFAULT false,
  npa_can_register_pagos boolean NOT NULL DEFAULT false,
  npa_can_approve_deals boolean NOT NULL DEFAULT false,
  npa_can_ajuste_cuadre boolean NOT NULL DEFAULT false,
  npa_can_nota_entrega boolean NOT NULL DEFAULT false,
  npa_can_admin boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  npa_can_view_crm boolean DEFAULT false,
  can_view_solicitudes boolean DEFAULT false,
  can_create_solicitudes boolean DEFAULT false,
  can_approve_solicitudes boolean DEFAULT false,
  can_view_mensajes boolean NOT NULL DEFAULT false,
  can_send_mensajes boolean NOT NULL DEFAULT false,
  can_delete_solicitudes boolean NOT NULL DEFAULT false,
  can_view_activity_log boolean NOT NULL DEFAULT false,
  can_view_cobranza boolean NOT NULL DEFAULT false,
  npa_can_view_inventory_finance boolean NOT NULL DEFAULT false,
  npa_can_view_management_pnl boolean DEFAULT false,
  tesoreria_can_pickup boolean NOT NULL DEFAULT false,
  tesoreria_can_dispatch boolean NOT NULL DEFAULT false,
  tesoreria_can_view_balance boolean NOT NULL DEFAULT false,
  tesoreria_can_replenish_cc boolean NOT NULL DEFAULT false,
  tesoreria_can_confirm_fx boolean NOT NULL DEFAULT false,
  tesoreria_can_request_salida boolean NOT NULL DEFAULT false,
  tesoreria_can_approve_salida boolean NOT NULL DEFAULT false,
  tesoreria_can_register_cc_gasto boolean NOT NULL DEFAULT false,
  tesoreria_admin boolean NOT NULL DEFAULT false,
  can_manage_usdt boolean NOT NULL DEFAULT false,
  tesoreria_can_register_ingreso boolean NOT NULL DEFAULT false,
  can_register_pagos_recibidos boolean DEFAULT false,
  can_cancel_pagos_recibidos boolean DEFAULT false,
  tesoreria_can_arqueo boolean NOT NULL DEFAULT false,
  tesoreria_can_request_cc_repo boolean NOT NULL DEFAULT false,
  npa_can_mark_lost boolean NOT NULL DEFAULT false,
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_permissions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
-- Included for the CRM → financing bridge (Tier 2): Claudia will create drafts here.
CREATE TABLE public.solicitudes_prestamo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  submitted_via text NOT NULL DEFAULT 'equipo'::text CHECK (submitted_via = ANY (ARRAY['equipo'::text, 'cliente_portal'::text])),
  created_by uuid,
  status text NOT NULL DEFAULT 'borrador'::text CHECK (status = ANY (ARRAY['borrador'::text, 'pendiente_docs'::text, 'documentos_completos'::text, 'analizando'::text, 'revision'::text, 'aprobado'::text, 'contrato_creado'::text, 'activo'::text, 'rechazado'::text, 'cancelado'::text])),
  solicitante_tipo text CHECK (solicitante_tipo = ANY (ARRAY['persona'::text, 'empresa'::text])),
  cliente_nombre text NOT NULL,
  cliente_apellidos text,
  cliente_cedula text NOT NULL,
  cliente_cedula_tipo text,
  cliente_email text,
  cliente_telefono text,
  cliente_direccion text,
  cliente_ciudad text,
  cliente_estado text,
  cliente_fecha_nacimiento date,
  cliente_estado_civil text,
  empleo_empresa text,
  empleo_cargo text,
  empleo_antiguedad_meses integer,
  empleo_ingreso_mensual_usd numeric,
  empresa_razon_social text,
  empresa_rif text,
  empresa_rep_legal_nombre text,
  empresa_rep_legal_cedula text,
  incluir_fiador boolean DEFAULT false,
  fiador_nombre text,
  fiador_apellidos text,
  fiador_cedula text,
  fiador_telefono text,
  fiador_empresa text,
  fiador_cargo text,
  fiador_ingreso_mensual_usd numeric,
  vehiculo_marca text DEFAULT 'KIA'::text,
  vehiculo_modelo text,
  vehiculo_anio integer,
  vehiculo_precio_usd numeric,
  inicial_usd numeric,
  monto_solicitado_usd numeric,
  plazo_meses integer,
  cuota_estimada_usd numeric,
  ai_snapshot jsonb,
  score numeric,
  score_verdict text CHECK (score_verdict = ANY (ARRAY['aprobar'::text, 'rechazar'::text, 'revision_manual'::text])),
  score_breakdown jsonb,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  decision text CHECK (decision = ANY (ARRAY['aprobado'::text, 'rechazado'::text])),
  decision_notes text,
  rejection_reason text,
  contrato_id uuid,
  contrato_creado_at timestamp with time zone,
  contrato_creado_by uuid,
  notificado_at timestamp with time zone,
  notificado_by uuid,
  notificacion_canal text,
  islr_ingreso_anual_usd numeric,
  islr_fecha_declaracion date,
  islr_anio integer,
  referencias_bancarias_cantidad integer,
  referencias_bancarias_calificacion text,
  otros_ingresos_usd numeric,
  otros_ingresos_descripcion text,
  propiedades_total_usd numeric,
  propiedades_descripcion text,
  cuentas_secundarias jsonb DEFAULT '[]'::jsonb,
  historial_deudas_activas_usd numeric,
  historial_puntaje text,
  cuota_mensual_usd numeric,
  ingreso_total_real_usd numeric,
  lti_ratio numeric,
  lti_verdict text CHECK (lti_verdict IS NULL OR (lti_verdict = ANY (ARRAY['excelente'::text, 'aceptable'::text, 'riesgoso'::text]))),
  lti_breakdown jsonb,
  empleo_ingreso_mensual_bs numeric,
  islr_ingreso_anual_bs numeric,
  incluir_conyuge boolean NOT NULL DEFAULT false,
  conyuge_nombre text,
  conyuge_apellidos text,
  conyuge_cedula text,
  conyuge_estado_civil text,
  conyuge_telefono text,
  conyuge_email text,
  CONSTRAINT solicitudes_prestamo_pkey PRIMARY KEY (id),
  CONSTRAINT solicitudes_prestamo_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT solicitudes_prestamo_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT solicitudes_prestamo_contrato_id_fkey FOREIGN KEY (contrato_id) REFERENCES public.cobranza_contratos(id),
  CONSTRAINT solicitudes_prestamo_contrato_creado_by_fkey FOREIGN KEY (contrato_creado_by) REFERENCES auth.users(id),
  CONSTRAINT solicitudes_prestamo_notificado_by_fkey FOREIGN KEY (notificado_by) REFERENCES auth.users(id)
);

-- NOTE: This is the CRM-relevant subset of the AutoCore database (crm_*, catalog,
-- inventory, rates, Meta ads, messaging logs, roles/permissions, bank_transactions,
-- financing). The full ~60-table schema (tesorería, cobranza pagos, compromisos,
-- pagos_recibidos, etc.) lives in the autocore-npa repo. VIEWS the bot reads that
-- are not defined here: v_inventory_disponible (over inventory_units, estado
-- EN_STOCK), v_kia_modelos (over kia_modelos where activo).
